### ISSUE TITLE
Bug: Priority system

### ISSUE THREAD

**Issue by davqvist** [Frinn38/Custom-Machinery#10]
Not sure if that is two seperate bugs, but I found 2 seperate issues regarding priority of recipes.

Case 1: A machine has two recipes, one requiring steam as only input, one requiring water as only input. Both have no priority provided.
https://pastebin.com/ayE5c608 https://pastebin.com/GLcHU2nj Machine: https://pastebin.com/9Fw7HKwK
Even if I provide it water, it defaults to the stream recipe.

Case 2: 
A machine has a bunch of recipes with different priorities. The more of a specific item there is in the input the faster the machine will be. The priority system works fine for the first iteration, but at the end of the recipe cycle it doesn't check priority again and prefers the same recipe over the one that is faster (I added more of the item in between).
Slowest recipe: https://pastebin.com/JeDsnhLz Fastest recipe: https://pastebin.com/Nfpt9fer Machine: https://pastebin.com/1YaA08Gw

**Comment by Frinn38** [comment]
For 2) this is "normal", the previous recipe is always checked first to avoid checking all recipes if possible. I didn't thought of the case you are describing, I will rework a bit the recipe selection system to make it prefer the recipe with higher priority over the previous pocessed recipe. 

For 1)  I may have forgot some checks in the fluid per tick requirement,  should be pretty easy to fix

**Comment by Frinn38** [comment]
Fixed in 0.2.3
