### ISSUE TITLE
[1.19.x] Crashes on load

### ISSUE THREAD

**Issue by andriihorpenko** [Frinn38/Custom-Machinery#100]
The client crashes sometimes with the following crash report. Can't say much, it just occurs frequently during game load. I would say 1 out of 10 launches.

[message-3.txt](https://github.com/Frinn38/Custom-Machinery/files/12110889/message-3.txt)

**Comment by Frinn38** [comment]
First update CM to the latest version (0.9.1) and then I will need the full debug.log file (after a crash).
You can find this file in the logs folder, if you use Curseforge you need to enable it in the launcher settings.

**Comment by andriihorpenko** [comment]
I think we should close this issue then as I’m currently unable to update to the latest version of CM as it brings KubeJS 6.1 support, and new KubeJS breaks other mods in the modpack, unfortunately. I’ll gladly reopen the issue if the crash persists on latest version of CM.

**Comment by turnerlewis** [comment]
I can't find the working mod file which supports KubeJS 6.0

Another mod in my modpack requires 6.0 for the time being. Could you make it public please?

Edit: I'm using Fabric on 1.19.2
