### ISSUE TITLE
[1.19.2 Fabric] Crashed on the server

### ISSUE THREAD

**Issue by in1t1a1** [Frinn38/Custom-Machinery#102]
This will not crash on the client side
[latest.log](https://github.com/Frinn38/Custom-Machinery/files/12189089/latest.log)

**Comment by DenisMasterHerobrine** [comment]
Can confirm the same issue on dedicated server, looks like Custom Machinery tries to load a clientside class, while it shouldn't do it on server side.

Fabric API 0.76.0+1.19.2
Custom Machinery 1.19.2-0.9.1

**Comment by Frinn38** [comment]
Should be fixed in CM 0.9.2
