### ISSUE TITLE
When to update 1.20.1?

### ISSUE THREAD

**Issue by REYXTE** [Frinn38/Custom-Machinery#106]
simple question。

**Comment by Frinn38** [comment]
Never, If I ever update to 1.20+ (which is not planned at the moment) it will be for the latest version, so 1.20.4 currently.

**Comment by EvanHsieh0415** [comment]
> Never, If I ever update to 1.20+ (which is not planned at the moment) it will be for the latest version, so 1.20.4 currently.

To work better with KubeJS, I recommend 1.20.1 or 1.20.4.
