### ISSUE TITLE
[bug] progress custom texture not working ( 1.16.5)

### ISSUE THREAD

**Issue by RobinErza** [Frinn38/Custom-Machinery#107]
i want add my own texture for progress empty to filled but the texture are not working , it stay vanilla

**Comment by Frinn38** [comment]
Did you correctly set the `"emptyTexture"` and `"filledTexture"` properties in your progress gui element ?
Anyway 1.16.5 is not supported anymore, you can come to the discord if you need help making your machine work but if there is a bug I won't fix it.
