### ISSUE TITLE
[Suggestion-1.18.2] Randomly output one item among multiple output items

### ISSUE THREAD

**Issue by xiakkto** [Frinn38/Custom-Machinery#113]
I would like to have a feature: when multiple items are set to output simultaneously, only one output is randomly selected. This would create a mechanism similar to a lottery. Implementing this feature with CraftTweaker is quite cumbersome. Could you add this functionality?

**Comment by Frinn38** [comment]
Already possible, use a loot table.
https://frinn.gitbook.io/custom-machinery-1.18/mod-integrations/kubejs/recipes/loot-table
