### ISSUE TITLE
[Compatibility] itemzoom renders within inventory while in machine GUI

### ISSUE THREAD

**Issue by ChiefLogan3010** [Frinn38/Custom-Machinery#114]
When Custom Machinery and ItemZoom are both installed, hovering over an item while in a custom machine GUI will render the item inside the inventory, rather than to the left like in other GUIs.

Inside other GUIs: ![2024-01-14_22 51 36](https://github.com/Frinn38/Custom-Machinery/assets/28235561/8b9dc2ae-b559-4049-9eb0-eef9bf76aff0)
Inside Custom Machinery GUI: ![2024-01-14_22 47 01](https://github.com/Frinn38/Custom-Machinery/assets/28235561/526861d7-10a9-4a84-9909-ef468ac01007)

**Comment by Frinn38** [comment]
Fixed for the next update (0.9.10).
![Screenshot_3](https://github.com/Frinn38/Custom-Machinery/assets/32675710/9da5795b-ce60-42e9-927c-dfa3a2841c5f)
