### ISSUE TITLE
[Suggestion] Make the structure creator tool use an area select

### ISSUE THREAD

**Issue by ogmon1243** [Frinn38/Custom-Machinery#115]
Would it be possible to either change or add another tool to be able to do an area box-style selection instead of the individual block selection style the structure creator tool has? Large structures or structures that have blocks that aren't accessible without breaking something to reach them are very annoying to define through the current structure creator.

**Comment by Frinn38** [comment]
Maybe one day, but don't expect it soon.
I note the suggestion, but multiblock type features aren't a priority.
