### ISSUE TITLE
[1.18.2 Fabric] Crashed on the server

### ISSUE THREAD

**Issue by Canbinlol** [Frinn38/Custom-Machinery#117]
This is almost a duplicate of Issue #102 , except on a deferent minecraft version. Will not crash on client side. The modpack is Create: Stella but changed Jade version to Jade-1.18.2-fabric-5.100.0 and Jade Addon version to JadeAddons-1.18.2-fabric-2.1.0. Tried CM version 0.7.6 and version 0.8.7 and both will cause crash with similar log.
Full server log:
[2024-02-13-6.log](https://github.com/Frinn38/Custom-Machinery/files/14269258/2024-02-13-6.log)
[2024-02-13-3.log](https://github.com/Frinn38/Custom-Machinery/files/14269289/2024-02-13-3.log)

**Comment by Frinn38** [comment]
Most likely I fixed it only for 1.19 version of the mod, I will backport the fix to 1.18 soon.

**Comment by Canbinlol** [comment]
> Most likely I fixed it only for 1.19 version of the mod, I will backport the fix to 1.18 soon.

Another important thing is that it won't crash if CM is pared with jade 5.99.10 and jade addon 2.0.1, only updating these two mods will cause crash. I hope this will help.

**Comment by Frinn38** [comment]
Fixed in CM-1.18.2-0.8.8
