### ISSUE TITLE
Exemple

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Frinn38/Custom-Machinery#12]
Can you put on github or curseforge a download a datapack and a resourcepack like exemple machine ?

**Comment by Frinn38** [comment]
There are already : 
[Test Datapack](https://github.com/Frinn38/Custom-Machinery/tree/1.16.5/test_datapack)
[Test Resourcepack](https://github.com/Frinn38/Custom-Machinery/tree/1.16.5/test_resourcepack)
