### ISSUE TITLE
[1.18] Craft Processor, Same Item in Multiple Slots Bug

### ISSUE THREAD

**Issue by bobrob2004** [Frinn38/Custom-Machinery#121]
There's a bug when a machine has the craft processor and you have the same item in multiple slots.  It'll craft the item with only one of the input items.  I'm also using Kubejs.  So for example, I have the recipe:

event.recipes.custommachinery.custom_craft("calculator:basic_calculator", Item.of("minecraft:coal", 2))
	.requireItem(Item.of("minecraft:charcoal", "input1"))
	.requireItem(Item.of("minecraft:charcoal", "input2"))

It'll craft the coal with only one charcoal.

**Comment by Frinn38** [comment]
Sorry but 1.18 is not supported since a long time, this bug is already fixed in newer versions of the mod.
