### ISSUE TITLE
Multiblock like working idea.

### ISSUE THREAD

**Issue by sysyss** [Frinn38/Custom-Machinery#122]
my idea is add Requirement call "hatch".
it is see target block's inventory and 
check/consume/trans/replace/add
 some kind 
energy/fluid/item/exp/else.
this mod is aleady can have no fuciton machine like custom chest so why not?

**Comment by Frinn38** [comment]
Any kind of multiblock features is not planned at the moment, I'm not against that idea but that's not a priority right now so don't count on it soon.
