### ISSUE TITLE
[1.21.1]Recipes problem

### ISSUE THREAD

**Issue by carloanselmini** [Frinn38/Custom-Machinery#123]
In neoforge 21.1.77 minecraft version 1.21.1 the machine recipes in the test datapack do not get processed, even if the ingredients are all in their place, the machines just stay in idle state without processing the recipe, the GUI works but when I hover the tanks or the machine state at the top right there is no mouse overlay with details, I tested the mod alone so I think there should be no conflict with other mods

**Comment by Frinn38** [comment]
It's probably just the example datapack being very outdated, I made it back in 1.16 and even if I try to not break compat between versions as much as possible it's probable I overlooked something.
I will check it when possible and update it.

**Comment by carloanselmini** [comment]
Thank you for your answer, after your suggestion i tried to recreate the stone_generator following the 1.21 wiki but no recipe is processed, i even tried to add a button and the relative condition in the recipe in order to start the recipe, it stays always idle no matter what
