### ISSUE TITLE
[BUG] zenscript item output for machines is broken.

### ISSUE THREAD

**Issue by donoya** [Frinn38/Custom-Machinery#13]
The documentations says I only need 2 arguments, but when I run /ct format, it says I need 4. After adding 1.0 and true to the arguments, it gives an error saying it can't cast IItemStack to MCItemStack. When I checked in the crafttweaker documentation, it didn't seem like 'MCItemStack' exists. I assume this is a bug.
I'm using custom machinery version 1.16.5-0.3.1 and crafttweaker version 1.16.5-7.1.0.313.

**Comment by Frinn38** [comment]
The `produceItem()` method indeed takes 4 arguments, the last 2 are optional.
The last argument is missing on the wiki, I forgot to add it so it's a boolean that define if the recipe should consume the item or it's durability (true for durability, false for item count). It is optional and default to false so it should works without having to specify it.

The `MCItemStack` thing is my error, I assumed that CT item brackets `item:mod:id` makes a `MCItemStack` which is a CT thing but I guess that's not the case, will check that for the next update.

**Comment by Frinn38** [comment]
The MCItemStack error is fixed in 0.3.5, the wiki is updated (at least the part about CT integration for item requirements).
Sorry that this took a bit of time but this issue is now fixed.
