### ISSUE TITLE
Customisable JEI Support

### ISSUE THREAD

**Issue by Jerome226** [Frinn38/Custom-Machinery#16]
![image](https://user-images.githubusercontent.com/55724525/125207762-0beecc80-e25c-11eb-9408-3881403496b3.png)

Here a example.
I would like to remove the upgrades slots and the energy bar from the JEI Integration without changing the machine itself because i like the GUI like it is right now.

thanks for the mod anyways.

**Comment by Frinn38** [comment]
Well, I can make it possible to override the jei recipe gui to not use the machine gui, and use it's own gui elements instead. And if the override is not specified it fallback to the machine gui.
I add that to my todo list.

**Comment by Jerome226** [comment]
Perfect. Hope to see that implemented!

**Comment by Frinn38** [comment]
Now possible in Custom Machinery 0.4.1, see [the wiki page](https://github.com/Frinn38/Custom-Machinery/wiki/JEI-Recipe-GUI) for more informations.
