### ISSUE TITLE
Allow item tags in the filter property of Item Slot Components

### ISSUE THREAD

**Issue by Faeranne** [Frinn38/Custom-Machinery#17]
I'm wanting to add some custom items to a machine that all have the same item group tag, but currently this requires putting all of them in the filter property one-by-one.  Being able to just whitelist the tag would make this much easier.

**Comment by Frinn38** [comment]
Yeah that's planned, same for fluids in fluid component, blocks in structure requirements...
So almost everything that use items/fluids/blocks

**Comment by Frinn38** [comment]
Done in 0.4.3
