### ISSUE TITLE
jeiRequirements should override anything in requirements

### ISSUE THREAD

**Issue by Faeranne** [Frinn38/Custom-Machinery#18]
When making recipies, I'm needing to override the NBT data when displaying as a JEI recipe, but instead of overriding the requirements list, jeiRequirements, concats, causing anything added there that is already added to just be dropped.  Not only is this less useful than overriding, it's also not consistant with how JEI adjustments already work, since the JEI tag in a machine replaces the gui tag.

**Comment by Frinn38** [comment]
yeah I guess I can just make the jeiRequirements completly override the "requiremens" like it's done for the machine gui

**Comment by Faeranne** [comment]
I'd offer a PR, but I can't get gradle to behave.  SSL errors left and right trying to get the requirements.  Not a deal breaker while I develop the mod pack, so I'll just keep an eye here.

**Comment by Frinn38** [comment]
Done in 0.4.3
