### ISSUE TITLE
Allow Item or Fluid requirements to be set to Amount 0.

### ISSUE THREAD

**Issue by Faeranne** [Frinn38/Custom-Machinery#19]
Maybe this isn't the right way to think about it, but I'm thinking, allow either requirement to have an amount 0, so that is needs to be present, but isn't consumed during crafting?  I'll admit this is going beyond my understanding of Forge, so idk if that's already possible, or if it can't be done in the current Forge structure, so feel free to let me know if it's not a good idea.

**Comment by Frinn38** [comment]
What if you set the item/fluid amount to 1 and then put the chance to 0, in theory the recipe will check if there is at least 1 item/mb of fluid in the machine and then not consume it.

**Comment by Faeranne** [comment]
That works great.  I'll stick with that for now.
