### ISSUE TITLE
Machines not associated with recipes in JEI

### ISSUE THREAD

**Issue by Goldenlion5648** [Frinn38/Custom-Machinery#2]
The only way to find this recipe was by searching for recipes for gravel (or uses for stone). Kind of different issue, but only the stone generator shows in JEI, but even when clicked the recipes that can be made with it are not shown.

![image](https://user-images.githubusercontent.com/32916571/118017679-e6f5e000-b324-11eb-97e6-c618a555b647.png)

**Comment by Frinn38** [comment]
I forgot to add the machines items as recipe catalysts, that's why they are not displayed on the left and why it doesn't show the possibles recipes for the machine when you rightclick/press U on it in JEI/inventory.
This is added in 0.1.2
