### ISSUE TITLE
How to use the mod on the server

### ISSUE THREAD

**Issue by MarilynPalmer** [Frinn38/Custom-Machinery#20]

**Comment by Frinn38** [comment]
Exactly the same as on client, put the mod in the mods folder and your datapack containing your machines/recipes json into the datapacks folder.

**Comment by MarilynPalmer** [comment]
![image](https://user-images.githubusercontent.com/86869254/127246713-b5992925-bc56-47b2-bbe0-2a72f370b7b2.png)

**Comment by Frinn38** [comment]
That should be fixed in the next update.

**Comment by Frinn38** [comment]
Fixed in 0.4.3
