### ISSUE TITLE
GUI elements not updating

### ISSUE THREAD

**Issue by jamesjimmy88** [Frinn38/Custom-Machinery#25]
Energy bars that are being charged and progress bar elements don't get updated / start their animation when a recipe starts when the player is already looking at the GUI. There is no issue if the interface is opened while the recipe is progressing, but the problem will obviously happen again at the start of the next recipe.
Tested with Custom Machinery Ver. 0.4.4 on Forge 36.2.2

**Comment by Frinn38** [comment]
Fixed in 0.4.5
