### ISSUE TITLE
Redstone requirement breaks recipes

### ISSUE THREAD

**Issue by Faeranne** [Frinn38/Custom-Machinery#27]
Adding a redstone component to the requirements causes the recipe to constantly run regardless of any input.

**Comment by Frinn38** [comment]
Can't reproduce this, in the 0.4.6 update I changed a bit how redstone requirement/component works, if this is still not fixed in 0.4.6 please send me a recipe and machine json that have this issue.

**Comment by Frinn38** [comment]
I guess it's fixed, if not you can reopen the issue.
