### ISSUE TITLE
Unable to synthesize in the server

### ISSUE THREAD

**Issue by MarilynPalmer** [Frinn38/Custom-Machinery#29]
Invalid in the server
![image](https://user-images.githubusercontent.com/86869254/128660044-530a04e3-09ce-41c7-ba16-cbc24453b674.png)

**Comment by Frinn38** [comment]
What exactly don't work ?

**Comment by MarilynPalmer** [comment]
Cannot produce items

**Comment by Frinn38** [comment]
I didn't realize it was one of the example machine recipe lol, the test datapack is way outdated. I fixed that.
