### ISSUE TITLE
Item "Dupe" with multiple item input slots

### ISSUE THREAD

**Issue by Freebi85** [Frinn38/Custom-Machinery#3]
Hey There 😄 
I'm trying to make something like an assembler with multiple input slots.
But when using more then one input slot all items which are inserted after the first one will transform into the same like the first one. (Only when shift clicking!)

Here is a small video.
https://user-images.githubusercontent.com/42634622/118159093-e5a7de80-b41c-11eb-8ccc-0cd63b53f2c0.mp4

Forge 1.36.17
Custom-Machinery 0.1.1

**Comment by Frinn38** [comment]
Hello, well that's awkward but none of my 3 test machines have multiple input slots so I completly missed this bug x)
Anyway this is fixed in 0.1.2, thanks for the report.
