### ISSUE TITLE
Weird shadow on machines

### ISSUE THREAD

**Issue by jamesjimmy88** [Frinn38/Custom-Machinery#30]
Machines project a very noticeable shadow on adjacent machines - the shadow doesn't go away even after placing a light source directly on the affected machines; this issue only affects machine blocks that are facing south. This happens both for dummy machines, machines using a _block_ field for their appearance and machines using a custom model.
![2021-08-13_17 11 37](https://user-images.githubusercontent.com/58559532/129381490-6255d26a-1878-46c6-a527-24d20e354ddd.png)
![2021-08-13_17 13 11](https://user-images.githubusercontent.com/58559532/129381499-163449db-4e22-4d7c-beaf-000b8355a3c7.png)
Edit: forgot to specify versions: Tested on version 0.4.6 on Forge 36.2.2

**Comment by Frinn38** [comment]
I'm aware of this bug, I spent hours trying to fix it before giving up... Someday I will try again but since it happen only when the machine facing is south and ambient occlusion (smooth lightning) is on this is not a priority.

**Comment by Frinn38** [comment]
"""Fixed""" in 0.4.7, I disabled Ambient Occlusion  for the machine so no weird shadows but no shadow at all.
I know ths solution is far from perfect but all I tried didn't work and fixing that will require a very precise knowledge about the minecraft model render engine and a lot of maths...
