### ISSUE TITLE
Light emission is not working

### ISSUE THREAD

**Issue by jamesjimmy88** [Frinn38/Custom-Machinery#31]
As per title - unless I'm doing something wrong, a machine using the fields _lightMode_ and _lightLevel_ will never light up, no matter what values are used.

Tested on version 0.4.6 on Forge 36.2.2

**Comment by Frinn38** [comment]
I didn't like the way I implemented machine light emission anyway... It rely on a very bad syncing system that I deleted in 0.4.6 to use a better method. That's probably why the light emission does not work anymore.
Thanks for reminding me, I will try to take a look and remake this system for the next update.

**Comment by Frinn38** [comment]
Fixed in 0.4.7
