### ISSUE TITLE
Question: Is it possible to add custom blockstates like "running" to the machine?

### ISSUE THREAD

**Issue by yuesha-yc** [Frinn38/Custom-Machinery#32]
I want to see if blockstates can be added to represent the machine's status. This is purely a question, or enhancement suggestion. 

Btw, I love the mod so much. It's the most customizable mod I've seen so far!

**Comment by Frinn38** [comment]
Currently the status of the machine is written in the machine nbt, I thought of making it a blockstate but I'm not sure of what would be the benefits and also changing a blockstate very often is not really optimised.
So maybe if I find a utility to do like that but this is not really a necessity for now.

**Comment by yuesha-yc** [comment]
I think it is kinda important to display a change of status without GUI. Adding blockstate or adding some NBT support in the "appearance" component of machine could be helpful.
