### ISSUE TITLE
Can I repost the mod on Chinese MC Forum?

### ISSUE THREAD

**Issue by yuesha-yc** [Frinn38/Custom-Machinery#33]
This is an amazing mod and I would like more people to know about. However in China most people visit mcbbs.net to find new mods. I would like to repost a thread on the forum showcasing your mod. I will not provide a second distribution link except your original curseforge release page.

**Comment by Frinn38** [comment]
As long as you don't repost the jar file directly on another website you can do as you wish.
I don't want people to repost the file because if a malicious person add a virus to it and repost it (not saying that it's your case) that would ruin the player's fun.
