### ISSUE TITLE
Tree Absorber - does not recognize Tree

### ISSUE THREAD

**Issue by gneumann333** [Frinn38/Custom-Machinery#38]
Hi,

I play this mod in Techopolis (Skyblock) 
I placed the Tree absorber and built the tree, directly on the ABsorber (no Dirt) with 5 Oak Logs and 50 Oak Leaves 
When i Open the, i click on the arrow and the the green plus and i can see the Build outline for the Tree
There were no Red Warning and no white Places left but the Absorber still says "Idle" 
It is powered.
I tried several time and also with Spruce.
No Luck
Any tips or hints what im doing wrong?

**Comment by Frinn38** [comment]
I don't know, I never played Techopolis.
Custom Machinery is a mod that let pack makers create machines for their modpacks, but it doesn't add any machines on it's own.
You should ask the Techopolis modpack dev how the machine they created works.
