### ISSUE TITLE
multiplayer, fluid not showing in machine gui.

### ISSUE THREAD

**Issue by glaDexLex** [Frinn38/Custom-Machinery#39]
multiplayer not always show fluid in gui, but TOP show.
![fluid](https://user-images.githubusercontent.com/40333134/157799490-08369b97-4455-4153-a08f-0d15a0f53a38.png)

**Comment by Frinn38** [comment]
Sorry for not replying sooner. 
That look like a server/client desync issue, these are very random and hard to reproduce.
TOP show the server value (which is correct) and the gui show the client value (which is outdated and was somehow not synced).
I will try to fix it but unless I can get a reproductible test case it will be hard to know what cause this issue.

**Comment by Frinn38** [comment]
That kind of issues should not happen anymore in 1.18 versions
