### ISSUE TITLE
JEI output item is rendered in input slot

### ISSUE THREAD

**Issue by Freebi85** [Frinn38/Custom-Machinery#4]
Hello 😄 

It's me again^^ Found out when using multiple input slots, the machine output is rendered in an input slot as well when using JEI preview for the recipe^^

The recipe works fine and the machine runs correctly. It's just a visual thing in this case.

In this example below, the gravel is output.

![pic](https://user-images.githubusercontent.com/42634622/118242280-72927c80-b49d-11eb-8bde-27e635f79f18.PNG)

Cheers 🍺

**Comment by Frinn38** [comment]
finally fixed in 0.2.4
