### ISSUE TITLE
About the negative coordinates of GUI

### ISSUE THREAD

**Issue by StarZeroRI** [Frinn38/Custom-Machinery#42]
For single player games, I can fill in negative coordinates in the GUI and turn on the machine. But if you put it on the server, you can't open the GUI of the machine.
Or let it support a larger interface，Difficulties were encountered in making machines with more functions

**Comment by Frinn38** [comment]
Negative coordinates are not allowed in gui elements, don't know why it work in singleplayer because it shouldn't :/
The current size of the machine GUI is 256*192px, thought it was okay but I can make that customisable so you will be able to add more gui elements.

**Comment by Frinn38** [comment]
Added in 0.5.8
