### ISSUE TITLE
Is it possible to combine multiple blocks and use a model together

### ISSUE THREAD

**Issue by StarZeroRI** [Frinn38/Custom-Machinery#43]
Is it possible to combine multiple blocks and use a model together.
It's like Immersive Engineering.
![image](https://user-images.githubusercontent.com/89684932/165515973-bbdab694-a37c-49c2-a80c-bc631eca8d5a.png)
This is a machine model that takes up 5x5x5 blocks

**Comment by Frinn38** [comment]
That's not possible right now, and probably won't be in the future.
This mod is not really intended to create multiblocs machines, maybe when all other features are added and bugs fixed I will start implementing some multiblocks features such as this, but that won't be before a very long time.

Note: As long as the model can be loaded by Minecraft/Forge you can use it, so having a model bigger than 1 block is technically possible, but that wont stop the rendering of other blocks around the machine and the model will not have a collision box.
