### ISSUE TITLE
The model cannot be displayed with shaderpacks

### ISSUE THREAD

**Issue by StarZeroRI** [Frinn38/Custom-Machinery#45]
![image](https://user-images.githubusercontent.com/89684932/166460627-179d62ac-62c8-491c-9bf6-63a43cb56a73.png)

**Comment by StarZeroRI** [comment]
![image](https://user-images.githubusercontent.com/89684932/166461289-e739d50c-9276-4b62-985b-e7b68e3fb0d8.png)
This is a comparison picture

**Comment by Frinn38** [comment]
Optifine is not supported, remove it and you should be good.

**Comment by accessdenied0** [comment]
> ![image](https://user-images.githubusercontent.com/89684932/166461289-e739d50c-9276-4b62-985b-e7b68e3fb0d8.png) This is a comparison picture

This may be unrelated but these models looks amazing... you planing to do a modpack? I would love to see and play with these models in a pack...

**Comment by StarZeroRI** [comment]
> 



> > ![image](https://user-images.githubusercontent.com/89684932/166461289-e739d50c-9276-4b62-985b-e7b68e3fb0d8.png) This is a comparison picture
> 
> This may be unrelated but these models looks amazing... you planing to do a modpack? I would love to see and play with these models in a pack...

This is a model I made for one of my servers. It may appear as a modpack one day in the future, but I don't have much time to continue making it now, and the progress is slow.

**Comment by Frinn38** [comment]
It seems to work using [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) to load shaders (tested with BSL Shaderpack).
Closing anyway as Optifine is not supported.
