### ISSUE TITLE
[1.18.2] Crash when opening Machine GUI

### ISSUE THREAD

**Issue by DerCommander323** [Frinn38/Custom-Machinery#49]
So I downloaded the Test Datapack and Resourcepack and added them to my game, which did work since the machine is there and showing fine but when i place it and open the GUI it will open but immediately freeze the game and then crash.

latest.log: https://mclo.gs/THvhtq0
custommachinery.log: https://mclo.gs/s3p01DR

Forge Version: 40.1.25 on MC 1.18.2
Mod Version: 1.18.2-0.6.0

**Comment by Frinn38** [comment]
Look like I used a class from kubejs instead of the one from mc without noticing... So the mod won't work without kubejs installed (on at least the machine gui).
Thanks for the report I will fix that soon.

**Comment by Frinn38** [comment]
Fixed in latest version (1.18.2-0.6.1)
