### ISSUE TITLE
Crash with Create mod

### ISSUE THREAD

**Issue by davqvist** [Frinn38/Custom-Machinery#5]
Crash: https://pastebin.com/j01UWFkL
Machine used: https://pastebin.com/x1KMs6eT
Machine has only this recipe: https://pastebin.com/NNEqaU2A

How to re-create:
Place Create Mechanical Pump
Place Pipe on pump output side
Place Machine on pipe

Forge 36.1.18
CM 0.1.2

**Comment by Frinn38** [comment]
Ah yes, not really create fault, more like forge that allow mods to try to get a machine capability before the tile is properly fully initialized. Anyway fixed in 0.1.3
