### ISSUE TITLE
[1.16.5] Increase energy capacity with upgrade

### ISSUE THREAD

**Issue by Z4RM** [Frinn38/Custom-Machinery#55]
Hello,

I would to increase the energy capacity of a machine with an upgrade, is it possible ? Thank you by advance.

Cordially,
Z4RM

**Comment by Frinn38** [comment]
Hi, this feature is planned but not implemented yet, upgrade can only affect inputs and outputs of a recipe, but not the components of a machine.
Also this feature most likely will never be implemented in 1.16.5, as I don't have the time to dev 2 versions so new features will only come for 1.18.2
