### ISSUE TITLE
[Suggestion] Ability to both push and pull items, fluids, and energy to/from adjacent block entities.

### ISSUE THREAD

**Issue by mouseas** [Frinn38/Custom-Machinery#57]
From what I understand, Custom Machinery machines can accept inputs pushed into them by other blocks like pipes and hoppers, and will allow other blocks to pull outputs out of them, but they do not have the ability to pull inputs from adjacent inventories, nor push to adjacent inventories.

I'd like to see that ability added. A basic use case could be making a speed hopper that moves up to 16 items at a time, or a fluid hopper. Another case could be a machine that pulls from a chest on the left, smelts the item, and pushes the result into a chest on the right, without need for hoppers or pipes.

It would also be nice to have the option of letting the player configure that input/output push/pull behavior like how Thermal Series does its machines, or having it be fixed/hardcoded for the machine.

**Comment by Frinn38** [comment]
I can add that feature, although I don't like it. I think that transport must be reserved to pipes and machines shouldn't try to push or pull things themselves. It will generate more lag too.
But that mod is about letting the users create the machines they want, without limitations (as far as possible) so for now I will add that to my to-do list and eventually add it in a future update.

Closing as this is not an issue and I keep suggestions in a separate list (discord).
