### ISSUE TITLE
[1.18.2] Custom Machine ignores Output/Input modes for slots when using hoppers and other extractors

### ISSUE THREAD

**Issue by Irbynx** [Frinn38/Custom-Machinery#60]
Custom Machine ignores Output/Input modes for component slots when dealing with external item manipulators. Tested this with vanilla Hoppers and Create's Funnels. This results in input slots having their items extracted by hoppers/other extractors while output slots can be filled by hoppers/other extractors in spite of this being undesirable behavior. Essentially, in spite of setting proper modes (input/output), they act as if the mode wasn't set.

Attaching the machine file that I've used that produces this result - maybe the issue is with specifics.

[tradetato.txt](https://github.com/Frinn38/Custom-Machinery/files/9132164/tradetato.txt)

**Comment by Frinn38** [comment]
in the last version, the `mode` property is only used for recipes, to know which slot can be used to consume or produce items.
If you want to enable/disable input/output for a slot you must use the `config` property.
Example : for a slot that only allow inputs 
```json
"config": {
    "default": "input"
}
```
More info on the wiki : https://frinn.gitbook.io/custom-machinery-1.18/misc/config

**Comment by Irbynx** [comment]
I think the page that provides details on the item component should be changed to reflect that, then, as it still describes old behavior in the "mode" property description. Referring to configs from that description would be quite helpful too.

**Comment by Frinn38** [comment]
True, the wiki was not up to date about the mode property description. That's fixed now.
