### ISSUE TITLE
[Suggestion] Add push/pull option for input/output

### ISSUE THREAD

**Issue by Tismas** [Frinn38/Custom-Machinery#61]
The thing I love about thermal machines is that they can auto input/output.
You can place a drawer above and below the machine for a very neat visual hint of what's happening without wiring issues.
It'd be awesome to have such an ability in the custom machines.

**Comment by Frinn38** [comment]
Yeah that's planned

**Comment by Frinn38** [comment]
Added in update 0.7.0
