### ISSUE TITLE
CraftTweaker Tag is "Cannot invoke"

### ISSUE THREAD

**Issue by xiakkto** [Frinn38/Custom-Machinery#62]
I want create one CraftTweaker Recipe and use .requireItemTag().
But a Cannot invoke error occurs on build.
This is picture:
![slimetag](https://user-images.githubusercontent.com/109633750/179866433-93701acd-9758-4ff7-9a01-3b82ffb323e0.png)

![error](https://user-images.githubusercontent.com/109633750/179866416-5723b9ac-4ed2-41dc-a166-a7f82a9c79d2.png)

**Comment by Frinn38** [comment]
What version are you using ? this bug was fixed a few versions ago.

**Comment by xiakkto** [comment]
1.16.5-0.5.8f

**Comment by Frinn38** [comment]
Just pushed an update (1.16.5-0.5.8g) with the fix (it was fixed only for 1.18 version until now).

**Comment by xiakkto** [comment]
ok,thanks
