### ISSUE TITLE
Suggestion: A dynamic text gui/jei component

### ISSUE THREAD

**Issue by mouseas** [Frinn38/Custom-Machinery#64]
It could be really useful for some recipes to have text elements where the text can be different per recipe.

For GUI component, it could display the text while the recipe is running.

For JEI component, it would display the text in the JEI recipe.

When a recipe doesn't define a value for the text component, it would use the default value from the component's definition in the machine, or be blank when no default is specified.

I also note that the `custommachinery:text` component doesn't appear in JEI recipes, even when explicitly included in the `jei` element in the machine definition. It would be helpful if there was a way to get it to display in JEI recipes, such as when trying to label different slots. In one case, I have a "Source" and a "Substrate" slot in one of my machine's recipes, and I'd like to be able to include those labels in JEI without having to use a texture element.

**Comment by mouseas** [comment]
And now that I think about it, it would be useful to have dynamic texture components which differ per recipe, too. For example, if some recipes require a heat source and others do not, the heat-requiring recipes could show one image with a flame while the non-heat-requiring recipes could show another image with an empty flame outline.

**Comment by Frinn38** [comment]
Forgot to reply, now it's possible as any recipe can add or replace gui elements when processing.
