### ISSUE TITLE
Placing blocks in other dimensions will crash

### ISSUE THREAD

**Issue by xiakkto** [Frinn38/Custom-Machinery#65]
I used CraftTweaker and wrote .dimensionBlacklist("minecraft:the_nether") in the .zs.
But when I enter the Nether and place down this block, the game crashes
This is crash-reports：
[crash-2022-08-17_21.35.28-client.txt](https://github.com/Frinn38/Custom-Machinery/files/9363218/crash-2022-08-17_21.35.28-client.txt)

**Comment by Frinn38** [comment]
This crash report doesn't say anything about a custom machine :/ can you test again with just CM installed and provide the full debug.log file.

**Comment by xiakkto** [comment]
Sorry, it looks like there is a conflict with Inventory Profiles Next

**Comment by xiakkto** [comment]
Oh,no...
It still crashed...
![image](https://user-images.githubusercontent.com/109633750/185744415-fb43833b-717c-45d5-9795-1e074abfb708.png)
So where do I check the CM log?

**Comment by Frinn38** [comment]
Under the logs folder there should be a "debug.log" file, upload it here after a crash.
If that file is not present and you're using curseforge or another launcher you need to go in the launcher's settings and enable it, then restart the game and the file will be here.

**Comment by xiakkto** [comment]
[minecraft-exported-crash-info-2022-08-21T01-47-45.zip](https://github.com/Frinn38/Custom-Machinery/files/9387787/minecraft-exported-crash-info-2022-08-21T01-47-45.zip)
Oh,emmm...
this?

**Comment by Frinn38** [comment]
No, this file is not named "debug.log"
And I can't open zip files on my phone so it's useless.

**Comment by xiakkto** [comment]
[debug.log](https://github.com/Frinn38/Custom-Machinery/files/9387888/debug.log)
This?

**Comment by Frinn38** [comment]
Yes that's the good log.
You seems to have a lot of mods installed, which makes the log very hard to read. Can you test with the minimal amount of mods (ideally just forge, CT and CM) and upload the log again.
Can you also send your machine json and the full ct recipe ?

**Comment by xiakkto** [comment]
[debug.log](https://github.com/Frinn38/Custom-Machinery/files/9388818/debug.log)

**Comment by Frinn38** [comment]
you still have a lot of mods installed, try with only Custom Machinery and Crafttweaker and send me the log.
Also the machine json and recipe script please.

**Comment by xiakkto** [comment]
Sorry, it is now available again
