### ISSUE TITLE
The custom machine upgrade created by Crafttweaker is invalid

### ISSUE THREAD

**Issue by xiakkto** [Frinn38/Custom-Machinery#66]
I'm sorry I sent another issues, but now I have a new problem: the upgrade written by Crafttweaker has no effect.
Normally it should speed up and consume FE, but it doesn't, it just puts it in that position and has no effect whatsoever.
![image](https://user-images.githubusercontent.com/109633750/186515811-28ce2d0a-0f04-4c80-8491-65b463cee547.png)

I hope what I wrote is correct...
![image](https://user-images.githubusercontent.com/109633750/186517457-e001db26-9c64-406a-8c38-c112e48fcc88.png)
![image](https://user-images.githubusercontent.com/109633750/186517923-2607afd6-7033-432c-8d3f-18c65cf6e136.png)

**Comment by Frinn38** [comment]
Do you declare the slot as an upgrade slot ? 
You should do that by adding `"variant": "custommachinery:upgrade"` inside the item component json.
Also, +30% recipe duration mean the recipe will be 30% slower, not faster.

**Comment by xiakkto** [comment]
Ah... But it hasn't slowed down either...
Now that I've modified it, it still hasn't changed.
![image](https://user-images.githubusercontent.com/109633750/186538454-6b67233c-8e2f-4663-885f-fec7f6f5bd27.png)
![image](https://user-images.githubusercontent.com/109633750/186538712-3d6c3f3a-2941-4ad5-bfde-6fde29ffa7a6.png)
It is indeed custommachinery:upgrade

**Comment by Frinn38** [comment]
ok there is indeed an issue with CT integration for upgrade, if you don't specify a "chance" (4th argument of any of the `mulInput`, `mulOutput`, `addInput` or `addOutput` method) it use 0 by default, which mean the upgrade modifier is never applied.

I will fix that quickly, as a temporary solution you can set the chance yourself by using for example : 
`.mulInput(<requirementtype:custommachinery:speed>, 0.2, "", 1)`

Note that the "target" (3rd parameter) is needed to specify the "chance" (4th parameter) as that how CT works.

**Comment by Frinn38** [comment]
Should be fixed in latest version (1.16.5-0.5.8i)
