### ISSUE TITLE
[1.16.5]Fuel GUI looks like it has some issues

### ISSUE THREAD

**Issue by xiakkto** [Frinn38/Custom-Machinery#68]
![QQ截图20220930182840](https://user-images.githubusercontent.com/109633750/193250967-36a5bf65-b21f-451c-8750-c0b8a20de6b6.png)

**Comment by Frinn38** [comment]
look like the filled texture is missing, can you send your machine json and debug log files ?

**Comment by Frinn38** [comment]
Closed as 1.16 is not supported anymore, if you have the same issue in 1.18 or later feel freem to open another issue.
