### ISSUE TITLE
[Suggestion] Add commas to energy amounts

### ISSUE THREAD

**Issue by Nevrai** [Frinn38/Custom-Machinery#69]
It’s difficult to see how much energy a recipe requires due to the lack of commas, so I think simply adding commas (and a space before the “FE” whilst you’re at it) would do wonders in making the JEI recipe screen more readable. I think the same should also be done for the machine GUI itself. Since the JEI GUI uses the machine GUI, I’m assuming it only has to be changed in the machine GUI.

![Custom Machinery](https://user-images.githubusercontent.com/59761487/194398230-a024b4c3-028b-4313-896f-87c6a8a5de10.png)

**Game version:** 1.18.2

**Comment by Frinn38** [comment]
Good suggestion, that will be done in the next update : 
![image](https://user-images.githubusercontent.com/32675710/194675240-33dc94bd-89f2-450d-97db-aa0039e88446.png)
(E is Tech Reborn energy, for the forge version it show "FE" of course)
The same formatting will be applied for fluid amounts.

**Comment by Nevrai** [comment]
That is wonderful! Thank you.

**Comment by Frinn38** [comment]
Fixed in update 0.7.0
