### ISSUE TITLE
JEI lookup with multiple outputs

### ISSUE THREAD

**Issue by davqvist** [Frinn38/Custom-Machinery#7]
If a machine has multiple item outputs, you can only lookup the recipe by clicking on the last of those items in JEI.
So, e.g. a machine processes item a into item b and c, clicking on c (or pressing R while hovering over) shows the recipe, but clicking on b doesn't.

Forge 36.1.18
CM 0.1.3

**Comment by Frinn38** [comment]
Fixed in 0.1.4
