### ISSUE TITLE
[Suggestion] Show recipe’s energy usage in JEI, make ghost items more transparent, and add no-fluid-use upgrade

### ISSUE THREAD

**Issue by Nevrai** [Frinn38/Custom-Machinery#70]
### Suggestion 1: Show recipe’s energy usage in JEI

Currently, custom machines do not show how much energy they use per tick in JEI. They do show the `.requireEnergy` amount, which is just the initial start-up energy cost, but they do not show the energy per tick that is used for the recipe.

Currently, I have a custom JEI information page for each item saying how much time a recipe takes and how much energy it uses, but I think it would be incredible if the following could be implemented: display how much energy per tick a recipe uses as well as the total energy it will use over the whole duration when hovering over the progress element in JEI.

So, for example, if a recipe has a duration of **500** ticks and has `.requireEnergyPerTick(20)`, it will use 20 FE/t—or 10,000 FE in total. In that case, it should display, when hovering over the progress element in JEI, something like “20 FE/t - 10,000 FE total” (in addition to separately showing the initial `.requireEnergy` cost when hovering over the energy element in JEI.

I think that would be super useful.

### Suggestion 2: Make ghost items more transparent or add an option to configure it

The “ghost items” that you can set to appear in an item slot in the machine’s GUI aren’t _that_ transparent, so it almost looks like the items are actually in the machine when they’re not. I think it’d be nice if they were either a little more transparent or if you could adjust it yourself in the machine’s JSON file.

## Suggestion 3: Add no-fluid-use upgrade

I think it’d be really nice to be able to create an upgrade that, when inserted into the machine, makes it not use any fluid. Out of all these suggestions, I’d want this one to be implemented the most, and I hope this is something you could consider adding.

**Comment by Frinn38** [comment]
First, consider going to the discord server for sharing your suggestions/asking if X feature is present, Github is fine for issues but not really suited for support.
About your suggestions:

1. The energy consumed per tick when using `.requireEnergyPerTick` is already displayed in jei, when you hover the energy bar with the mouse cursor it will show "Energy: X FE per tick".
However I just realized that this tooltip is the same for both input and output mode for the energy requirement, I will improve that.
I keep the idea of having the tooltip displaying the total amount in addition to the rate, will add that too.

2. No problem, I will add that feature.

3. Pretty sure this is already possible with the current upgrade system, by making an upgrade that multiply the fluid amount by 0, I didn't tested it thought.

**Comment by Nevrai** [comment]
@Frinn38  Understood. I’ll keep that in mind and won’t submit any more suggestions to the issue tracker.

Anyway, regarding #1, it does not show the FE used per tick for me. All it shows is the initial energy cost (`.requireEnergy`) but not the `.requireEnergyPerTick` cost, which is set to `84` in this recipe, so it would use a total of about 150,000 FE as the duration is 1,800 ticks.

![Fgx8bLv](https://user-images.githubusercontent.com/59761487/194775390-e9f96e63-c46c-4b6d-a613-c382dc94ce39.png)

As for #3, I wasn’t aware you could do that. Thank you for letting me know!

**Comment by Frinn38** [comment]
1) I didn't thought you used both `.requireEnergy` and `.requireEnergyPerTick` ,  currently you recipe will consume 1000FE at the start, and then 84FE/t until the end, is that really what you want ? If so there is no way to show both the initial and per tick energy cost.
One gui element (here the energy bar) can only show one requirement (energy and energy-per-tick are 2 separate requirements) and that's not going to change soon as that would need to almost completely rewrite the jei integration.
So my advice here is just to not use both instant and per tick energy requirements in the same recipe.

2) That's done for the next update, you will be able to choose the transparency of the ghost item and even color it : 
![image](https://user-images.githubusercontent.com/32675710/195872107-b179de4c-818a-452b-926a-7bbfda79407a.png)
a stone ghost item with 20% opacity and red color vs a normal stone item.

**Comment by Nevrai** [comment]
Thanks for implementing configurability for the ghost item. That’s sweet!

As for the first thing, yes, I do intentionally use both, as I want the recipes to consume a certain amount of energy at the start and then a higher amount of energy over the course of the recipe. It’s unfortunate you can’t implement support for this, but it’s understandable. Now knowing this is why it’s not showing the energy usage in JEI, I suppose I should just not use both and rather just use `.requireEnergyPerTick`.

**Comment by Frinn38** [comment]
Fixed in update 0.7.0
