### ISSUE TITLE
Shift-clicking items into a machine doesn’t put them in the appropriate slots

### ISSUE THREAD

**Issue by Nevrai** [Frinn38/Custom-Machinery#71]
Currently, when I shift-click an item into my machine, it always goes into the first main item input slot. This isn’t ideal when you shift-click an upgrade or a “catalyst”-type item (I have a slot with a ghost item and a whitelist which always only accepts one specific item).

I placed the upgrade slots and the “catalyst” slot above all other item input slots in the JSON file, but shift-clicking an item does not place it in those slots, for some reason. I can place them in the slots _manually_, and everything works as expected. However, shift-clicking them does not place them in those slots. You’d expect the catalyst to be shift-clicked into the catalyst slot and the upgrades to go into the upgrade slots, but that’s not what’s happening. I suppose I could set a blacklist for the upgrades and catalyst for each regular item input slot, but that seems like an unnecessary workaround. I’m assuming this is a bug, although I may be doing something wrong. I’m not sure what, though, as it seems to me like the intended behaviour would be for the item to go into the slot that is defined first in the JSON file, but that’s not what is happening here.

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest)
* **Custom Machinery:** 0.6.7 (latest)

**Comment by Frinn38** [comment]
Currently when you shift-click an item in your inventory it simply goes in the first available slot that can contain this item (if the whitelist/blacklist of the slot allows it).

The "item" property of the slot is only intended to show an item in the slot gui texture, it doesn't have any priority or filtering properties, the `slot gui element` is basically only a texture, it can't affect what item goes in the machine inventory, this is the job of the `item component`. 
So yeah a blacklist/whitelist in the item component is the best you can have to affect in which slot the item will go when shift-clicked.

For making upgrades items prioritize upgrade slots when shift clicked it's possible, I will add that in the next update.

**Comment by Frinn38** [comment]
Fixed in update 0.7.0

**Comment by Nevrai** [comment]
Thank you!
