### ISSUE TITLE
Installing sodium will cause the block model to disappear.

### ISSUE THREAD

**Issue by wb26x** [Frinn38/Custom-Machinery#73]
Installing sodium will cause the block model to disappear.

This is after installing sodium.

https://user-images.githubusercontent.com/117894543/201037938-bf845e5e-c055-4be4-be8c-7b3591882ed1.mp4

This is sodium is not installed.

https://user-images.githubusercontent.com/117894543/201041564-97318f16-91fc-47c8-bf37-7019ccc1fb31.mp4

minecraft 1.18.2 Fabric+0.14.10
custommachinery-1.18.2-0.7.1-fabric
sodium-fabric-mc1.18.2-0.4.1+build.15

**Comment by Frinn38** [comment]
Ok, there was 2 problems here : 
- An error in my code, this will be fixed in the next update.
- You also need [Indium](https://www.curseforge.com/minecraft/mc-mods/indium) to make Sodium compatible with the Fabric renderer API that CM use.

**Comment by wb26x** [comment]
Oh, I forgot to tell you, I added indium to make it compatible with sodium.
If the next update has been fixed, that would be great.
Because I like this mod, thank you for your efforts.
Hopes the download volume will exceed 1 million.

**Comment by Frinn38** [comment]
Should be fixed in the new version (0.7.2) let me know if that's not the case.

**Comment by wb26x** [comment]
It working but like dont working.
I don't know how to describe it, so watch the video.

https://user-images.githubusercontent.com/117894543/202608273-2158b22d-e92f-4210-b06f-58352d5f374a.mp4
