### ISSUE TITLE
[1.18.2] Shift-clicking an item stack into an item slot bypasses the slot's maximum capacity

### ISSUE THREAD

**Issue by Kynake** [Frinn38/Custom-Machinery#75]
In the example datapack, the machine that turns cobble into diamonds is only supposed to accept a single cobble at a time, but you can bypass the item slot limit by shift-clicking the entire stack of cobble into the slot.
[slot_capacity_test.zip](https://github.com/Frinn38/Custom-Machinery/files/10370422/slot_capacity_test.zip)

**Comment by Frinn38** [comment]
Fixed for the next update.

**Comment by Kynake** [comment]
Works correctly for me now! It even distributes the items across slots if there are multiple of them. You can close this if you want
