### ISSUE TITLE
[1.18.2] Left or right-clicking an item stack into a slot bypasses the slot's filter

### ISSUE THREAD

**Issue by Kynake** [Frinn38/Custom-Machinery#76]
Came across another item slot bug while testing #75. Shift-clicking works correctly and will block the placement.

I modified the test datapack from #75 so that the machine is only  supposed to accept cobblestone, but with left or right click you can still put other items into the machine input slot.
[slot_filter_test.zip](https://github.com/Frinn38/Custom-Machinery/files/10416589/slot_filter_test.zip)

**Comment by Kynake** [comment]
Update: You can also bypass blacklist filters the same way. This one's setup to blacklist Andesite.
[slot_filter_test_blacklist.zip](https://github.com/Frinn38/Custom-Machinery/files/10416702/slot_filter_test_blacklist.zip)

**Comment by Frinn38** [comment]
Fixed in latest version (0.8.0)
