### ISSUE TITLE
[1.16.5]Incomplete JEI display in multiplayer games.

### ISSUE THREAD

**Issue by StarZeroRI** [Frinn38/Custom-Machinery#77]
Incomplete JEI display in multiplayer games.
As shown in the figure, the configuration is the same.
The machine can work normally to produce finished products, but it cannot be displayed in JEI
Single player game:
![0](https://user-images.githubusercontent.com/89684932/212678990-4169d957-10f3-41d3-9a85-268d879f6c42.png)
In the server:
![8](https://user-images.githubusercontent.com/89684932/212679780-2236ea67-1187-4094-ad25-9faf6f7fbaf8.jpg)

**Comment by Frinn38** [comment]
Sorry but 1.16.5 is not supported anymore, if you encounter the same problem in 1.18 or later feel free to open a new issue.
