### ISSUE TITLE
[1.18.2] Incorrect JEI display of energy GUI element

### ISSUE THREAD

**Issue by Kynake** [Frinn38/Custom-Machinery#78]
When a recipe that requires energy or energy per tick is displayed in JEI it doesn't follow the pattern defined in the custom `"filledtexture"` field of the energy GUI element. It does not use the same color for energy as the standard one and if the energy bar is not a rectangular shape it will 'overflow' the borders of the texture.

I've attached images of two examples of this behavior. The first example is one that I had intended to use in my machines and the second example is a more drastic one that I created for testing.

Normal:
![image](https://user-images.githubusercontent.com/20174739/214471969-dcd0e2d6-8066-4db8-89fe-c1ba721ac618.png)
![image](https://user-images.githubusercontent.com/20174739/214472062-6782ae34-e753-40f3-82be-74a96855ee0b.png)

JEI:
![image](https://user-images.githubusercontent.com/20174739/214472016-ac9ec6fa-81e9-4284-9bbc-58da18de172d.png)
![image](https://user-images.githubusercontent.com/20174739/214472213-73c7bafd-601b-4efd-acac-b353bf0c8a6d.png)

**Comment by Frinn38** [comment]
Sorry for the delay, this is fixed in the latest update (0.8.0)

**Comment by Kynake** [comment]
No worries, thanks for the fix!
