### ISSUE TITLE
[1.16.5] Error while serializing Gui Element

### ISSUE THREAD

**Issue by SheReyy** [Frinn38/Custom-Machinery#79]
Forge: 36.2.34
mod version: custommachinery-1.16.5-0.5.8k.jar
kubejs version: kubejs-forge-1605.3.19-build.299.jar

Hi. I'm trying to make a serverpack, but I'm having some issues with Custom Machinery. On singleplayer, I can see and use my machines without issues. However, when I join my server, my machines are not present. I have some quests involving these machines, and they're shown as `Some machine block`. Once you place them, they're Dummy Machines.

I'm using the same config/datapack on the client and the server. Am I missing something?

[Here](https://pastebin.com/YEHQ8jWw)'s the custom machinery log.
[Here](https://gist.github.com/IamRyan30/8e132247046ca157ba934ad30d7350f2) is the server log.

**Comment by Frinn38** [comment]
Fixed on the discord
