### ISSUE TITLE
Make a machine powered by Redstone signal.

### ISSUE THREAD

**Issue by liuseniubi** [Frinn38/Custom-Machinery#8]
Is there any possibility?

**Comment by Frinn38** [comment]
I can make a redstone requirement, to allow a recipe to run only when the machine receive a redstone signal or generate a redstone signal when the machine is running.
Added to my to-do list

**Comment by liuseniubi** [comment]
Sounds nice! Thanks in advance!

**Comment by Frinn38** [comment]
Added in CM 0.2.2
