### ISSUE TITLE
Crash During Init Phase

### ISSUE THREAD

**Issue by ThunderSphun** [Frinn38/Custom-Machinery#80]
[crash-2023-03-30_19.19.09-client.txt](https://github.com/Frinn38/Custom-Machinery/files/11114244/crash-2023-03-30_19.19.09-client.txt)

**Comment by ThunderSphun** [comment]
Seems to be only in the most recent version

**Comment by Frinn38** [comment]
My bad, I keep forgetting that the fabric version exist now.
Anyway this is fixed in latest update (0.8.1).
