### ISSUE TITLE
[Question] stacked input recipes

### ISSUE THREAD

**Issue by ThunderSphun** [Frinn38/Custom-Machinery#81]
I tried to add a recipe where one item gets "infused" with another item, and give the user a choice to infuse up to three items at the same time, making it cheaper. I added these with different recipes, but the one with 2 items takes priority over the one with three items, meaning it will always try to get 2 items, then 1 item, then 3 items, meaning that the recipe with 3 items can never be executed. adding in explicitly air, the machine gives an error, saying it has "not enough `minecraft:air`, 0 needed but 0 found". Is there a way to have some sort of empty slot, or make one recipe take priority over another?

**Comment by Frinn38** [comment]
You can set a higher priority to the machine with 3 items so it would be checked first.
If you use json the syntax is : `"priority": 2`  
If you use CT/KJS the syntax is `.priority(2)`
Higher priority mean the recipe is checked before the ones with lower priority, default is 0 and you can use negative values.
