### ISSUE TITLE
[Suggestion] The ability to create machines with crafttweaker 

### ISSUE THREAD

**Issue by ThunderSphun** [Frinn38/Custom-Machinery#83]
I think it would be a powerful addition if the machines can be made via crafttweaker. maybe contenttweaker is needed.

**Comment by Frinn38** [comment]
I won't add this feature.
The recipe support for CT already take too much time to support. If I add CT support for machines I would have to do the same for KubeJS and then doing tests, writing wiki and giving support for both (+ JSON).
I don't have the time to do that, or there would be an update every 6 months at best, let alone updating for newer versions of MC.
