### ISSUE TITLE
[Question] Jei Hidden (Continuation)

### ISSUE THREAD

**Issue by ThunderSphun** [Frinn38/Custom-Machinery#84]
In response to #82 I want to add that this does not seem possible for fabric 1.18, and from what i can gather it is not possible at all.
Lets say I want to add a recipe for diamonds, with a custom machine. i would do something like
```
mods.custommachinery.CMRecipeBuilder.create("custom:itemMaker", 0)
.requireItem(<item:minecraft:diamond)
.produceItem(<item:minecraft:diamond>*2)
.build("op_diamond_making");
```
and I would like to hide this specific recipe, I can either hide everything from this machine, or hide everything that produces diamonds, which is both what i do not want to do.
I also dont want to make a custom machine purely for this recipe

Please inform me if i am wrong, but from what i could find, this is not possible in the version where i want it

**Comment by Frinn38** [comment]
You can use this to hide recipes in jei using CraftTweaker : 
https://docs.blamejared.com/1.18/en/mods/JEITweaker/API/JEI#hideRecipe
The category ID should be your machine ID `custom:itemMaker` (btw uppercase is not allowed in machine ID.
The recipe ID should be `crafttweaker:op_diamond_making` for your example.

**Comment by ThunderSphun** [comment]
To use the JEI functionality I need JEITweaker, which isnt available for fabric 1.18

**Comment by Frinn38** [comment]
I see, my bad I thought JeiTweaker was included in CT.
I will add a way to mark a recipe as hidden in jei.

**Comment by Frinn38** [comment]
Added in latest version (0.8.2), use `.hide()` in your recipe, anywhere between `.create()` and `.build();` to make it not show in JEI.
```
mods.custommachinery.CMRecipeBuilder.create("custom:itemMaker", 0)
.requireItem(<item:minecraft:diamond)
.produceItem(<item:minecraft:diamond>*2)
.hide()
.build("op_diamond_making");
```
