### ISSUE TITLE
[Question] JEI Category Collapse

### ISSUE THREAD

**Issue by ThunderSphun** [Frinn38/Custom-Machinery#86]
I have created machines which can process a list of recipes. these machines are upgraded versions, with extra slots and more energy capacity etc. the problem i am running into is that i now have 7 jei categories for recipes, because each machine creates a category. this is unnecessary because all machines can use the same recipes. can the catalysts field maybe be expanded to hiding other categories, or adding a seperate option for that.

**Comment by ThunderSphun** [comment]
To give an example, lets say I want to make some sort of furnace. Tier 1 would be the same as vanilla (fuel slot, input, output), tier 2 would still have one fuel slot, but two input and output slots. I would like a JEI Category where the two input and output slots are visible, shows that it can be done with both the tier 1 and tier 2, and doesnt show a seperate category for just tier 1, and just tier 2.
it might look something like this
```json
"catalyst": {
"machines": ["furnace_tier_1", "furnace_tier_2"],
"exclusive": true,
"name": "mixed furnace tiers"
"jei": []
}
```
I added an extra jei field, as this shared category might have a different layout as default
This might also be nice as a seperate json file

**Comment by Frinn38** [comment]
I don't really understand the problem you're having, if all machines can process the same recipes can't you just hide all categories but one ?
Anyway Github isn't really fit for giving support, could you consider joining the discord instead, it will be easier to chat and try to find a way to achieve what you want.
