### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ChilledDayZ07** [Frinn38/Custom-Machinery#9]
Would it be possible to add a way of checking if the block is waterlogged and have it pull water from the world?

**Comment by Frinn38** [comment]
A block requirement that is able to check/place/break nearby blocks is planned, I didn't thought of waterlogged blocks but that's a good idea.

**Comment by ChilledDayZ07** [comment]
Yeah I was hoping to be able to create a water flow generator for FE

**Comment by Frinn38** [comment]
Added in 0.3.1, the machine can now check/place/replace/break/destroy nearby blocks
The machine still can't be waterlogged thought, implementing that is easy but it may break lot of things so I will have to do some testing before adding this feature.
