### ISSUE TITLE
Create mod integration

### ISSUE THREAD

**Issue by CebbyS** [Frinn38/Custom-Machinery#90]
Hi, are there any plans for Create mod integration?

It would be awesome to support custom machines powered by the Create rotational power. 

Ideas on how to do it:

1. For a single block, having it powered by a shaft, as implementing the gear or rotational components for models would make the implementation very complex. But having a component that consumes the Create rotational power does not seem so complex. I have not checked the API Create provides, but I think that there should be an interface that could be added to the machine instance.
2. Multiblock structures, having a Create block, like Mixer in the middle would automatically consume rotational power. Thus creating a condition that checks the rotational power for the Mixer, and only enables the custom machine controller to work if the rotational power is within a given range.

If this idea seems interesting or something that could be a good thing to include, I would be interested to investigate or help

**Comment by Frinn38** [comment]
Hi, I'm currently writing a Custom Machinery - Create addon, with it the machines will be able to consume and produce Create SU.

The Create API is basically inexistent and required many workaround on my end to make it compatible with CM, but it's progressing.
For now the machine will connect only to shafts and not to gears exactly for the reason you mentioned, making the machine model rotate is currently impossible and would require a huge rewrite of CM which is not planned yet (Geckolib support ?).

About multiblocks, this is not something CM can/will support, I suggest looking at Multiblocked and Masterful Machinery as they both allow making multiblocks and both have Create integration.

**Comment by CebbyS** [comment]
@Frinn38 awesome news, looking towards the addon, if any help needed, I would be happy to help
