### ISSUE TITLE
Bug - Using RF Tools Builder to Copy

### ISSUE THREAD

**Issue by theisen1337** [Frinn38/Custom-Machinery#93]
When trying to copy a machine from Custom-Machinery with RF Tools Builder it converts the machine into a Dummy.

To replicate this bug.
* Using mod pack ( Sky Capsule )
* Use Custom-Machinery machine ( Tier 2 Resource Generator )
* Copy using RF Tools Space Chamber Controller
* Setup End location to build copy. Setup RFT builder and resources needed.

Expected Outcome: Tier 2 Resource Generator
Actual Outcome: Dummy

RF Tools work with other modpacks well.

**Comment by Frinn38** [comment]
Found the issue, that's a bug in McJtyLib, I reported it in their issues : https://github.com/McJtyMods/McJtyLib/issues/158
