### ISSUE TITLE
Crash at startup when using with Canvas

### ISSUE THREAD

**Issue by ZZZank** [Frinn38/Custom-Machinery#94]
[crash-2023-06-27_19.09.35-client.txt](https://github.com/vram-guild/canvas/files/11881284/crash-2023-06-27_19.09.35-client.txt)

I have some knowledge about mixin, and I found a cretain part in crash report that's very likely to be the reason:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_778::custommachinery$getLightEmission with priority 1000 cannot inject into net/minecraft/class_778::method_3374(Lnet/minecraft/class_1920;Lnet/minecraft/class_1087;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLjava/util/Random;JI)Z merged by grondag.canvas.mixin.MixinModelBlockRenderer with priority 1000 [PREINJECT Applicator Phase -> custommachinery.fabric.mixins.json:ModelBlockRendererMixin from mod custommachinery -> Prepare Injections ->  -> redirect$zfh000$custommachinery$getLightEmission(Lnet/minecraft/class_2680;Lnet/minecraft/class_1920;Lnet/minecraft/class_1087;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;)I -> Prepare]`

Also: [the same issue in canva's side](https://github.com/vram-guild/canvas/issues/429)

**Comment by Frinn38** [comment]
The issue is on Canva's side, they use an @Overwrite mixin, making it incompatible with any mod that mixin in the same method.
They already fixed the issue in their Github, by using @Inject instead of @Overwrite. They just need to release a new 1.18 version.

**Comment by supsm** [comment]
The fix was merged a while ago and only recently backported to the 1.18 branch. Although we do still support older versions to an extent, they are not our top priority so they may have some issues.

p.s. it's canvas and not canva

**Comment by Frinn38** [comment]
Thanks for the precision, about your other massage in Canvas's issue tracker I was trying to point him to either here or my discord server so he can tell me exactly what issues he has with CM, sorry if my poor English failed to do that.

P.S. Noted, will call it Canvas from now.
