### ISSUE TITLE
Stacked fluid containers are deleted when inputting fluid

### ISSUE THREAD

**Issue by DarkYuan** [Frinn38/Custom-Machinery#95]
When holding a stack of fluid cells from FTB Industrial Contraptions, if you input fluid (left click) it acts as though you were only holding one cell, voiding the rest of the items completely.

![image](https://github.com/Frinn38/Custom-Machinery/assets/3029695/e3a475e2-8d27-4bc9-a3b9-6a853599ba29)
![image](https://github.com/Frinn38/Custom-Machinery/assets/3029695/84f7d02a-1f9a-462c-8a01-44f0f6923481)

**Comment by Frinn38** [comment]
It's not common for fluid handlers items to be stackable, in fact that's the first time I see that :/
I will see if I can fix that, I think the current code expect the fluid handler item to not be a stack.
