### ISSUE TITLE
[1.18.2] Energy Modifier Using Exponential Operation

### ISSUE THREAD

**Issue by bobrob2004** [Frinn38/Custom-Machinery#96]
I'm trying to make energy upgrades for machines that decrease the amount of energy used.  However, it seems to use the multiplication operation even though I put in the exponential operation.  Here is my code:

```
    "modifiers": [
    {
	    "requirement": "custommachinery:energy",
	    "mode": "input",
	    "operation": "exponential",
	    "modifier": 0.9
	}
```
I have a recipe that uses 20 FE.  So when I put in 8 upgrades, I expect the machine to only use 9 FE.  However, it uses 144.

**Comment by Frinn38** [comment]
I finally has some time to look on that, sorry for the delay.
I found several issues about how upgrades values were applied, most issues should be fixed in the next update.
Indeed the exponential modifier behaved as a multiplication modifier, that was fixed.
