### ISSUE TITLE
Bug - 1.16.5 wrong tooltip render coordinates

### ISSUE THREAD

**Issue by andrewchik0** [Frinn38/Custom-Machinery#97]
Hello, I am making a machine that will melt resources very quickly. I have encountered a bug with the rendering of the tooltip. If I create two "custommachinery:progress" elements with different coordinates in "components" and "jei", then the tooltip with "Show recipes" button will be rendered incorrectly.

### My json code:
```json
"gui": [
    {
      "type": "custommachinery:progress",
      "x": 78, // Coordinates different from jei element
      "y": 53,
      "emptyTexture": "custommachinery:textures/fire.png",
      "filledTexture": "custommachinery:textures/empty.png"
    }
    // Other components
  ],
  "jei": [
    {
      "type": "custommachinery:progress",
      "direction": "top",
      "x": 97,
      "y": 50
    }
    // Other components
  ],
```

### My crafttweaker code:
```java
for recipe in smelterRecipes {
  mods.custommachinery.CMRecipeBuilder.create('my_machines:smelter', 1)
    .requireItem(recipe.input)
    .produceItem(recipe.output)
    .build();
}
```

### Normal tooltip rendering in JEI:
![image](https://github.com/Frinn38/Custom-Machinery/assets/68250467/b452cfa0-8bd9-4067-a027-e675aacd18d0)

### Wrong tooltip rendering in GUI:
![image](https://github.com/Frinn38/Custom-Machinery/assets/68250467/638ccc6a-997c-4aff-9045-8b4b1d307b04)

I'd be very glad if you provide any solutions or bugfixes.

Also I noticed, that I can't use zero as a recipe duration in craft tweaker recipe builder.
It's unfortunate because I wanted to make machines that would process resources instantly.

**Comment by Frinn38** [comment]
I think that bug was fixed in 1.18.2 but the fix wasn't backported to 1.16.5, I will do that in the next update.

**Comment by andrewchik0** [comment]
Thank you very much. I'll be waiting.

Also wanted to ask if it would be possible to set zero as the recipe processing time in Craft Tweaker:
```java
mods.custommachinery.CMRecipeBuilder.create("namespace:machine", 0) // It does't work with 0 value
    .requireItem(recipe.input)
    .produceItem(recipe.output)
    .build();
```

**Comment by Frinn38** [comment]
Just pushed an update that fix this bug.
About using 0 ticks in recipes that isn't possible because the machine can only process a recipe once a tick (due to the way it's coded), it would also cause a huge risk of lag.
If you want the machine to produce items faster you can just increase the amount of items in the recipe, but anyway 1 tick is already really fast (0.05s), I don't see why you would need something faster than that.

**Comment by andrewchik0** [comment]
I'm sorry, but I sill have this issue in newest version.

Maybe I'm doing something wrong?
I can provide full json file if you can't reproduce this bug.
[creative_smelter.txt](https://github.com/Frinn38/Custom-Machinery/files/12017706/creative_smelter.txt)
GitHub does not support .json files so i renamed it into txt.

And also my recipe that i created with CraftTweaker:
```java
mods.custommachinery.CMRecipeBuilder.create('creative_machines:creative_smelter', 1)
  .requireItem(<item:minecraft:gold_ore>)
  .produceItem(<item:minecraft:gold_ingot>)
  .build();
```

**Comment by andrewchik0** [comment]
I just realized that this issue may be because we use different versions of JEI. 
Could that be the case?

### My mod list
![image](https://github.com/Frinn38/Custom-Machinery/assets/68250467/b0839816-76ea-4855-8a45-59a2a2c0518a)

**Comment by Frinn38** [comment]
My bad, I messed up in the fix I pushed earlier, I will reupload the file soon.
Re-open this so I won't forget tomorrow ^^"

**Comment by Frinn38** [comment]
That time it should be fixed. I reuploaded the file on curseforge under the same name: `Custom-Machinery-1.16.5-0.5.8l` You might have to delete and re-download it depending on which launcher you use.
